### ISSUE TITLE
TypeError: argument of type 'Word2Vec' is not iterable

### ISSUE THREAD

**Issue by filzahamjad** [yumeng5/WeSTClass#5]
running command: python main.py --dataset yelp --sup_source docs --model cnn
i'm getting this error: ### Input preparation ###
Loading existing Word2Vec model ./yelp/embedding...
Traceback (most recent call last):
  File "main.py", line 185, in <module>
    embedding_weights = train_word2vec(x, vocabulary_inv, args.dataset)
  File "main.py", line 46, in train_word2vec
    for key, word in vocabulary_inv.items()}
  File "main.py", line 46, in <dictcomp>
    for key, word in vocabulary_inv.items()}
TypeError: argument of type 'Word2Vec' is not iterable

**Comment by zengjl20** [comment]
Hello,  I have met the same problem. Have you solve this problem?

**Comment by filzahamjad** [comment]
@zengjl20 No. I went with conWea instead of this.

**Comment by ozyyshr** [comment]
I met the same problem. In my case, changing "embedding_model" to "embedding_model.wv" in line 46 of 'main.py' solved my problem.
